
   var  computersTablets=[
    {
    image:"https://img.gkbcdn.com/s3/b/xiaomi.jpg",
    url:"https://www.geekbuying.com/Brand/Xiaomi-1.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/lenovo.jpg",
    url:"https://www.geekbuying.com/Brand/Lenovo-7.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/huawei.jpg",
    url:"https://www.geekbuying.com/Brand/Huawei-9.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/teclast.jpg",
    url:"https://www.geekbuying.com/Brand/Teclast-21.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/chuwi.jpg",
    url:"https://www.geekbuying.com/Brand/Chuwi-22.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/alldocube.jpg",
    url:"https://www.geekbuying.com/Brand/AlldoCube-25.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/gpd.jpg",
    url:"https://www.geekbuying.com/Brand/GPD-26.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/ajazz.jpg",
    url:"https://www.geekbuying.com/Brand/Ajazz-50.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/minix.jpg",
    url:"https://www.geekbuying.com/Brand/MINIX-72.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/tronsmart.jpg?v=788944783",
    url:"https://www.geekbuying.com/Brand/Tronsmart-79.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/logitech.jpg",
    url:"https://www.geekbuying.com/Brand/Logitech-82.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/kingston.jpg",
    url:"https://www.geekbuying.com/Brand/Kingston-83.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/seagate.jpg",
    url:"https://www.geekbuying.com/Brand/Seagate-85.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/baseus.jpg",
    url:"https://www.geekbuying.com/Brand/Baseus-152.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/gamesir.jpg",
    url:"https://www.geekbuying.com/Brand/Gamesir-270.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/2003/mijia.jpg?v=501322930",
    url:"https://www.geekbuying.com/Brand/Mijia-447.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/netac.jpg",
    url:"https://www.geekbuying.com/Brand/Netac-466.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/razer.jpg",
    url:"https://www.geekbuying.com/Brand/Razer-640.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/rii.jpg",
    url:"https://www.geekbuying.com/Brand/Rii-651.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/stmagic.jpg",
    url:"https://www.geekbuying.com/Brand/Stmagic-736.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/one-netbook.jpg",
    url:"https://www.geekbuying.com/Brand/One-Netbook-741.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/cenava.jpg",
    url:"https://www.geekbuying.com/Brand/Cenava-760.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/yeelight.jpg",
    url:"https://www.geekbuying.com/Brand/Yeelight-823.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/Redmi.jpg",
    url:"https://www.geekbuying.com/Brand/Redmi-1067.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/AOSIMAN.jpg",
    url:"https://www.geekbuying.com/Brand/AOSIMAN-1110.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/gmk.jpg",
    url:"https://www.geekbuying.com/Brand/GMK-1230.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/kuu.jpg",
    url:"https://www.geekbuying.com/Brand/KUU-1245.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/xp-pen-6745ObjF.jpg",
    url:"https://www.geekbuying.com/Brand/XP-PEN-1264.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/pictek-67mC0Aau.jpg",
    url:"https://www.geekbuying.com/Brand/Pictek-1269.html"
    }
    ]
    