
    var wearableDevice =[
    {
    image:"https://img.gkbcdn.com/s3/b/xiaomi.jpg",
    url:"https://www.geekbuying.com/Brand/Xiaomi-1.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/huawei.jpg",
    url:"https://www.geekbuying.com/Brand/Huawei-9.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/cubot.jpg",
    url:"https://www.geekbuying.com/Brand/Cubot-13.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/makibes.jpg",
    url:"https://www.geekbuying.com/Brand/Makibes-52.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/amazfit.jpg",
    url:"https://www.geekbuying.com/Brand/AMAZFIT-53.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/ticwatch.jpg",
    url:"https://www.geekbuying.com/Brand/Ticwatch-55.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/hat-prince.jpg",
    url:"https://www.geekbuying.com/Brand/Hat-Prince-307.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/Haylou.jpg",
    url:"https://www.geekbuying.com/Brand/Haylou-963.html"
    },
    {
    image:"https://img.gkbcdn.com/s3/b/Logo/Redmi.jpg",
    url:"https://www.geekbuying.com/Brand/Redmi-1067.html"
    }
    ]
    